# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.broccoli.preprocess import MotionCorrection

def test_MotionCorrection_inputs():
    input_map = dict(args=dict(argstr='%s',
    ),
    device=dict(argstr='-device %d',
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    in_file=dict(argstr='%s',
    copyfile=False,
    mandatory=True,
    position=0,
    ),
    iterations=dict(argstr='-iterations %d',
    ),
    output=dict(argstr='-output %s',
    ),
    output_type=dict(),
    platform=dict(argstr='-platform %d',
    ),
    quiet=dict(argstr='-quiet',
    ),
    referencevolume=dict(argstr='-referencevolume %s',
    ),
    terminal_output=dict(nohash=True,
    ),
    verbose=dict(argstr='-verbose',
    ),
    )
    inputs = MotionCorrection.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value

def test_MotionCorrection_outputs():
    output_map = dict(motioncorrected_file=dict(),
    parameters_file=dict(),
    )
    outputs = MotionCorrection.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value

