# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.broccoli.preprocess import Smoothing

def test_Smoothing_inputs():
    input_map = dict(args=dict(argstr='%s',
    ),
    automask=dict(argstr='-automask',
    ),
    device=dict(argstr='-device %d',
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    fwhm=dict(argstr='-fwhm %s',
    ),
    ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    in_file=dict(argstr='%s',
    copyfile=False,
    mandatory=True,
    position=0,
    ),
    mask=dict(argstr='-mask %s',
    ),
    output=dict(argstr='-output %s',
    ),
    output_type=dict(),
    platform=dict(argstr='-platform %d',
    ),
    quiet=dict(argstr='-quiet',
    ),
    terminal_output=dict(nohash=True,
    ),
    verbose=dict(argstr='-verbose',
    ),
    )
    inputs = Smoothing.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value

def test_Smoothing_outputs():
    output_map = dict(mask_file=dict(),
    smoothed_file=dict(),
    )
    outputs = Smoothing.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value

